// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poda.Tablets.DAO;

#nullable disable

namespace SQL.Migrations
{
    [DbContext(typeof(DAOSQL))]
    [Migration("20220114125724_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Poda.Tablets.DAO.ProducerDBSQL", b =>
                {
                    b.Property<string>("GUID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GUID");

                    b.ToTable("ProducersRelation");
                });

            modelBuilder.Entity("Poda.Tablets.DAO.TabletDBSQL", b =>
                {
                    b.Property<string>("GUID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Display")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProducerGUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GUID");

                    b.ToTable("TabletsRelation");
                });
#pragma warning restore 612, 618
        }
    }
}
