// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poda.Tablets.DAO;

#nullable disable

namespace SQL.Migrations
{
    [DbContext(typeof(DAOSQL))]
    partial class DAOSQLModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Poda.Tablets.DAO.ProducerDBSQL", p =>
                {
                    p.Property<string>("GUID")
                        .HasColumnType("TEXT");

                    p.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    p.HasKey("GUID");

                    p.ToTable("ProducersRelation");
                });

            modelBuilder.Entity("Poda.Tablets.DAO.TabletDBSQL", t =>
                {
                    t.Property<string>("GUID")
                        .HasColumnType("TEXT");

                    t.Property<int>("Display")
                        .HasColumnType("INTEGER");

                    t.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    t.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    t.Property<string>("ProducerGUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    t.HasKey("GUID");

                    t.ToTable("TabletsRelation");
                });
#pragma warning restore 612, 618
        }
    }
}
